=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that the 7th triangle number, 28, is the first triangle number to have over five divisors.

Which is the first triangle number to have over five-hundred divisors?
=end

class Integer


	def triangle
		sum = 0
		(1..self).each { |i| sum = sum + i }
		sum
	end
	
	def divisors
		res=[1]
		2.upto(Math.sqrt(self).floor) do |i|
			if self % i == 0
				res << i
			end
		end
		res.reverse.each do |i|
			res << self / i
		end
		res.uniq
	end
end


i = 12_300
while i.triangle.divisors.size < 500 do
	i += 1
end

puts i.triangle



